version: '3.9'

services:
  postgres:
    env_file:
      - ../.env
    image: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

    logging:
      driver: none
